import React, { useState, useEffect } from "react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Loader2, AlertTriangle, Sparkles, Shield, Clock, CalendarDays, Server } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { FallingSnow } from "@/components/FallingSnow";

interface ForecastData {
    forecasts: {
        date: string;
        label: string;
        primary_prediction: string;
        probabilities: {
            open: number;
            delay: number;
            early_release: number;
            closure: number;
        };
    }[];
    last_updated: string;
}

const DISTRICTS = [
    { id: "LCPS", name: "Loudoun County (LCPS)" },
    { id: "FCPS", name: "Fairfax County (FCPS)" },
    { id: "PWCS", name: "Prince William (PWCS)" }
];

const PREDICTION_CONFIG: Record<string, { icon: string; color: string; bgGradient: string }> = {
    "Open": {
        icon: "🏫",
        color: "text-emerald-100",
        bgGradient: "from-emerald-700/40 to-teal-600/20",
    },
    "Delay": {
        icon: "⏱️",
        color: "text-blue-100",
        bgGradient: "from-blue-600/50 to-indigo-600/30",
    },
    "Early Release": {
        icon: "🌅",
        color: "text-amber-100",
        bgGradient: "from-amber-600/40 to-orange-500/20",
    },
    "Closure": {
        icon: "❄️",
        color: "text-indigo-100",
        bgGradient: "from-indigo-600/60 to-purple-700/50",
    }
};

const ProgressBar = ({ label, percentage, colorClass }: { label: string, percentage: number, colorClass: string }) => (
    <div className="space-y-1.5">
        <div className="flex justify-between text-xs font-bold uppercase tracking-widest text-white/50">
            <span>{label}</span>
            <span>{percentage.toFixed(1)}%</span>
        </div>
        <div className="h-3 bg-white/10 rounded-full overflow-hidden">
            <motion.div
                initial={{ width: 0 }}
                animate={{ width: `${percentage}%` }}
                transition={{ duration: 1, ease: "easeOut" }}
                className={`h-full rounded-full ${colorClass}`}
            />
        </div>
    </div>
);

export const SnowDayPredictor = () => {
    const [loading, setLoading] = useState(true);
    const [data, setData] = useState<ForecastData | null>(null);
    const [error, setError] = useState<string | null>(null);
    const [dayIndex, setDayIndex] = useState(1);
    const [selectedDistrict, setSelectedDistrict] = useState(DISTRICTS[0]);

    // Hardcoded fallback forecast — used if the GitHub Actions hasn't run yet
    // or the JSON fetch fails on first deploy. Regenerated by scripts/predict.py.
    const FALLBACK_FORECAST: ForecastData = {
        forecasts: [
            { date: "2026-03-02", label: "Monday, Mar 02", primary_prediction: "Open", probabilities: { open: 80.6, delay: 1.9, early_release: 4.9, closure: 12.5 } },
            { date: "2026-03-03", label: "Tuesday, Mar 03", primary_prediction: "Open", probabilities: { open: 68.5, delay: 18.0, early_release: 5.5, closure: 8.0 } },
            { date: "2026-03-04", label: "Wednesday, Mar 04", primary_prediction: "Delay", probabilities: { open: 29.8, delay: 56.9, early_release: 4.6, closure: 8.7 } }
        ],
        last_updated: "2026-03-02 21:49:04"
    };

    useEffect(() => {
        const fetchForecast = async () => {
            try {
                // Fetch the static JSON generated by GitHub Actions every 2 hours
                const res = await fetch('/data/forecast.json');
                if (!res.ok) throw new Error("Failed to load ML forecast");
                const json = await res.json();
                setData(json);
            } catch (err: any) {
                // Gracefully fall back to the last-known forecast built into the app
                console.warn("Could not load live forecast, using built-in fallback:", err);
                setData(FALLBACK_FORECAST);
            } finally {
                setLoading(false);
            }
        };
        fetchForecast();
    }, []);

    const forecast = data?.forecasts[dayIndex];
    const cfg = forecast ? PREDICTION_CONFIG[forecast.primary_prediction] : null;

    // Get the maximum probability percentage dynamically
    const maxProb = forecast ? Math.max(...Object.values(forecast.probabilities)) : 0;

    return (
        <div className="w-full bg-gradient-to-br from-slate-900 to-indigo-950 text-white rounded-3xl overflow-hidden shadow-2xl relative border border-white/10 font-sans shadow-indigo-900/20">
            <FallingSnow count={40} />

            <div className="relative z-10 p-6 md:p-10 min-h-[600px] flex flex-col">

                {/* HEADER */}
                <div className="flex justify-between items-start mb-8 border-b border-white/10 pb-6">
                    <div className="space-y-2">
                        <h2 className="text-4xl md:text-5xl font-black tracking-tight text-white drop-shadow-xl">
                            Snow Day ML Predictor
                        </h2>
                        <div className="flex items-center gap-2 text-sm font-bold uppercase tracking-widest text-emerald-300">
                            <Shield className="w-4 h-4 text-emerald-400" />
                            <span>Powered by XGBoost Multi-Class AI</span>
                        </div>
                    </div>
                    <div className="hidden md:flex flex-col items-end gap-1 text-[10px] font-bold uppercase tracking-widest text-white/40">
                        {data?.last_updated && (
                            <div className="flex items-center gap-1 text-indigo-300">
                                <Server className="w-3 h-3" />
                                <span>Updated: {data.last_updated}</span>
                            </div>
                        )}
                        <span>Open-Meteo V1</span>
                    </div>
                </div>

                {/* CONTROLS */}
                <div className="space-y-4 mb-8">
                    <div className="flex flex-col md:flex-row gap-3">
                        <div className="flex-1 bg-white/5 backdrop-blur-md rounded-xl p-1 pl-4 flex items-center border border-white/10">
                            <span className="text-white/50 mr-2 text-[10px] font-bold uppercase tracking-widest">District</span>
                            <Select
                                value={selectedDistrict.id}
                                onValueChange={(id) => setSelectedDistrict(DISTRICTS.find(d => d.id === id) || DISTRICTS[0])}
                            >
                                <SelectTrigger className="bg-transparent border-none text-white font-bold text-base w-full focus:ring-0 shadow-none">
                                    <SelectValue />
                                </SelectTrigger>
                                <SelectContent className="bg-slate-900 border-indigo-500/20 text-white font-bold">
                                    {DISTRICTS.map(d => (
                                        <SelectItem key={d.id} value={d.id}>{d.name}</SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>

                        <Select value={dayIndex.toString()} onValueChange={(v) => setDayIndex(parseInt(v))}>
                            <SelectTrigger className="w-full md:w-64 bg-white/5 backdrop-blur-md border border-white/10 text-white font-bold rounded-xl h-auto py-3">
                                <div className="flex items-center gap-2">
                                    <CalendarDays className="w-4 h-4 text-indigo-300" />
                                    <SelectValue />
                                </div>
                            </SelectTrigger>
                            <SelectContent className="bg-slate-900 border-indigo-500/20 text-white font-bold">
                                {data?.forecasts.map((f, i) => (
                                    <SelectItem key={i} value={i.toString()}>{f.label} {i === 0 ? '(Today)' : i === 1 ? '(Tomorrow)' : ''}</SelectItem>
                                )) || (
                                        <>
                                            <SelectItem value="0">Today</SelectItem>
                                            <SelectItem value="1">Tomorrow</SelectItem>
                                            <SelectItem value="2">2 Days Out</SelectItem>
                                        </>
                                    )}
                            </SelectContent>
                        </Select>
                    </div>
                </div>

                {/* ERROR */}
                {error && (
                    <motion.div
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        className="bg-red-500/20 border border-red-500/40 rounded-xl p-6 text-center text-white font-bold mb-6"
                    >
                        <AlertTriangle className="w-8 h-8 mx-auto mb-2 text-red-300" />
                        {error}
                    </motion.div>
                )}

                {/* RESULTS */}
                <AnimatePresence mode="wait">
                    {loading ? (
                        <motion.div key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="flex flex-col items-center justify-center py-24 text-indigo-300 space-y-4">
                            <Loader2 className="w-12 h-12 animate-spin" />
                            <div className="font-bold uppercase tracking-widest text-sm">Loading ML Inferences...</div>
                        </motion.div>
                    ) : forecast && cfg ? (
                        <motion.div
                            key="result"
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            className="space-y-6"
                        >
                            {/* MAIN VERDICT CARD */}
                            <div className={`p-8 md:p-12 rounded-3xl bg-gradient-to-br ${cfg.bgGradient} border border-white/20 shadow-2xl relative overflow-hidden flex flex-col items-center text-center`}>
                                <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-30 mix-blend-overlay" />
                                <div className="relative z-10 w-full max-w-2xl">

                                    <div className="inline-block px-4 py-1.5 mb-6 rounded-full text-xs font-bold uppercase tracking-widest border bg-white/10 text-white border-white/20 backdrop-blur-sm shadow-xl">
                                        Primary Prediction
                                    </div>

                                    <div className="text-7xl md:text-8xl mb-4">{cfg.icon}</div>

                                    <h1 className={`text-4xl md:text-5xl lg:text-6xl font-black tracking-tight leading-none ${cfg.color} mb-2`}>
                                        {maxProb.toFixed(1)}% Chance of <br className="hidden md:block" /> {forecast.primary_prediction}
                                    </h1>

                                    <p className="text-white/60 font-medium uppercase tracking-widest text-sm mt-4">
                                        For {forecast.label}
                                    </p>

                                    {/* MULTI_CLASS PROBABILITIES */}
                                    <div className="mt-12 w-full bg-slate-900/60 p-6 rounded-2xl border border-white/10 backdrop-blur-xl space-y-4">
                                        <div className="text-[10px] font-black uppercase tracking-widest text-white/50 text-left mb-2">
                                            Outcome Probabilities
                                        </div>
                                        <ProgressBar
                                            label="Closure (Full Snow Day)"
                                            percentage={forecast.probabilities.closure}
                                            colorClass="bg-gradient-to-r from-purple-500 to-indigo-400"
                                        />
                                        <ProgressBar
                                            label="Delay (2-Hour)"
                                            percentage={forecast.probabilities.delay}
                                            colorClass="bg-gradient-to-r from-blue-500 to-sky-400"
                                        />
                                        <ProgressBar
                                            label="Early Release"
                                            percentage={forecast.probabilities.early_release}
                                            colorClass="bg-gradient-to-r from-orange-500 to-amber-400"
                                        />
                                        <ProgressBar
                                            label="Open (Normal Day)"
                                            percentage={forecast.probabilities.open}
                                            colorClass="bg-gradient-to-r from-teal-500 to-emerald-400"
                                        />
                                    </div>

                                </div>
                            </div>
                        </motion.div>
                    ) : null}
                </AnimatePresence>
            </div>
        </div>
    );
};
